FROM --platform=$BUILDPLATFORM golang:1.25.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG VERSION=v0.8.7
RUN CGO_ENABLED=0 \
    go build \
    -ldflags="-w -s -X main.Version=${VERSION}" \
    -trimpath \
    -o /lanpaper \
    ./main.go

FROM alpine:3.20
RUN apk --no-cache add ca-certificates tzdata
COPY --from=builder /lanpaper /lanpaper
COPY --from=builder /app/static /static
COPY --from=builder /app/config /config

EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s CMD ["/lanpaper", "/health"] || exit 1
ENTRYPOINT ["/lanpaper"]
